export const myConfig = {
    height: 3000,
    width: 2500,
    automaticRearrangeAfterDropNode: true,
    collapsible: false,
    directed: false,
    focusZoom: 1,
    freezeAllDragEvents: true,
    highlightDegree: 1,
    highlightOpacity: 0.2,
    linkHighlightBehavior: true,
    maxZoom: 1,
    minZoom: 1,
    nodeHighlightBehavior: true,
    panAndZoom: true,
    staticGraph: false,
    staticGraphWithDragAndDrop: false,
    d3: {
        alphaTarget: 0.05,
        gravity: -400,
        linkLength: 300,
        linkStrength: 1,
        disableLinkForce: false
    },
    node: {
      color: "#d3d3d3",
      fontColor: "black",
      fontSize: 12,
      fontWeight: "normal",
      highlightColor: "red",
      highlightFontSize: 12,
      highlightFontWeight: "bold",
      highlightStrokeColor: "SAME",
      highlightStrokeWidth: 1.5,
    //   labelProperty: "name",
      mouseCursor: "pointer",
      opacity: 1,
      renderLabel: true,
      size: 450,
      strokeColor: "none",
      strokeWidth: 1.5,
      svg: "",
      symbolType: "circle"
    },
    link: {
      color: "#d3d3d3",
      fontColor: "red",
      fontSize: 10,
      fontWeight: "normal",
      highlightColor: "blue",
      highlightFontSize: 8,
      highlightFontWeight: "bold",
      mouseCursor: "pointer",
      opacity: 1,
      renderLabel: false,
      semanticStrokeWidth: false,
      strokeWidth: 4,
      markerHeight: 6,
      markerWidth: 6,
      strokeDasharray: 0,
      strokeDashoffset: 0,
      strokeLinecap: "butt",
      type: "CURVE_SMOOTH"
    }
};